[package]
name = "tiny-interp"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Tree-walking interpreter for Tiny"

[dependencies]
tiny-ast.workspace = true
tiny-lexer.workspace = true
thiserror.workspace = true

[dev-dependencies]
tiny-parser.workspace = true
tiny-sema.workspace = true
